In [1]:
import numpy as np

In [2]:
# 1-D array

one_dim_arr = np.array([10, 12])
print(one_dim_arr)

[10 12]


In [3]:
b = np.arange(3)
print(b)

[0 1 2]


In [5]:
c = np.arange(0,100,5)
print(c)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [6]:
lin_space_arr = np.linspace(0,100,5)
print(lin_space_arr)

[  0.  25.  50.  75. 100.]


In [8]:
lin_space_arr_int = np.linspace(0,100,5, dtype=int)
print(lin_space_arr_int)

[  0  25  50  75 100]


In [10]:
char_arr = np.array(['Welcome to Math for ML!'])
char_arr

array(['Welcome to Math for ML!'], dtype='<U23')

In [11]:
d = np.array([[1,2,3],[4,5,6]])
print(d.ndim)
print(d.shape)
print(d.size)

2
(2, 3)
6


In [ ]:
two_dim_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dim_arr[:1])  # first row
# both comma and separate rectangular brackets work for slicing and indexing
print(f"second row second column element of 2-D Arr (using two rectangular brackets) = {two_dim_arr[1][1]}")  # second row second column # this is indexing
print(f"second row second column element of 2-D Arr (using comma in one rectangular bracket) = {two_dim_arr[1,1]}")  # second row second column # this is indexing
print(f"complete 2nd row = {two_dim_arr[1, :]}")  # second row all columns
print(f"all rows of third column = {two_dim_arr[:, 2]}")  # all rows third column 

[[1 2 3]]
second row second column element of 2-D Arr (using two rectangular brackets) = 5
second row second column element of 2-D Arr (using two rectangular brackets) = 5
complete 2nd row = [4 5 6]
all rows of third column = [3 6 9]


In [23]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

print(a1)
print(a2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [24]:
vstackked = np.vstack((a1, a2))
print("Vertically stacked array:")
print(vstackked)

Vertically stacked array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
hstackked = np.hstack((a1, a2))
print("Horizontally stacked array:")
print(hstackked)

Horizontally stacked array:
[[1 2 5 6]
 [3 4 7 8]]


In [27]:
hsplitted = np.hsplit(vstackked, 2)
print("Horizontally splitted arrays:")
for arr in hsplitted:
    print(arr)

Horizontally splitted arrays:
[[1]
 [3]
 [5]
 [7]]
[[2]
 [4]
 [6]
 [8]]
