In [1]:
import numpy as np

In [2]:
A = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype=np.float64)
b = np.array([-10, 0, 17], dtype=np.float64)

In [3]:
print("Matrix A:")
print(A)
print("Vector b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
Vector b:
[-10.   0.  17.]


In [4]:
print(f"Shape of Matrix A: {A.shape}")
print(f"Shape of Vector b: {b.shape}")

Shape of Matrix A: (3, 3)
Shape of Vector b: (3,)


In [5]:
# to find the solution for the three unknowns and which satisfies the 3 equations simultaneously
x = np.linalg.solve(A, b)
print("Solution x:")
print(x)
# to verify the solution
print("Verification (A @ x):")
print(A @ x)

Solution x:
[ 1.  4. -2.]
Verification (A @ x):
[-10.   0.  17.]


In [6]:
# shape of x
print(f"Shape of Solution x: {x.shape}")

Shape of Solution x: (3,)


In [8]:
determinant_of_A = np.linalg.det(A)
print(f"Determinant of A: {determinant_of_A:.2f}")

Determinant of A: -60.00


In [9]:
C = np.array([
    [1, 1, 1], 
    [0, 1, -3], 
    [2, 1, 5]
], dtype=np.float64)

d = np.array([2, 1, 0], dtype=np.float64)

np.linalg.solve(C, d)

LinAlgError: Singular matrix

In [10]:
np.linalg.det(C)

0.0

In [14]:
# 1. Tell NumPy to hide scientific notation and force 2 decimal places
np.set_printoptions(suppress=True, precision=2)

weights = np.array([
    [0.8, 1.2, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.5, 0.6, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 1.1, 0.9]
], dtype=np.float64)
input_vector = np.array([35, 2, 1500000, 300000, 2, 5000000], dtype=np.float64)

print("Input Vector Shape:", input_vector.shape)
print("Weights Shape:", weights.shape)

def neural_network(weights, input_vector):
    return weights.dot(input_vector)

prediction = neural_network(weights, input_vector)
print(f"Neural Network Prediction: {prediction}")

Input Vector Shape: (6,)
Weights Shape: (3, 6)
Neural Network Prediction: [     30.4 2430000.  4500002.2]
